driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[resolver::default]
    attributes: { "resolver": { "nameservers": ["8.8.8.8"]}}
  - name: force_unlink
    run_list:
      - recipe[resolver::default]
    attributes: { "resolver": {
            "deactivate_resolvconf": true,
            "nameservers": ["8.8.8.8"]}}
